"""add sorties and sortie waypoints

Revision ID: 11620fb9de27
Revises: 8db027860662
Create Date: 2026-09-12 18:29:42.255153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11620fb9de27'
down_revision: Union[str, Sequence[str], None] = '8db027860662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written -- same as b286fc804e53/8db027860662: autogenerate doesn't detect
    # native Postgres ENUM value changes.
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'in_grid'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'out_grid'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'ops_check'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('sortie_number', sa.Integer(), nullable=True),
    sa.Column('mission_number', sa.String(length=50), nullable=True),
    sa.Column('pic_name', sa.String(length=100), nullable=True),
    sa.Column('engine_start_event_id', sa.UUID(), nullable=True),
    sa.Column('engine_stop_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('fk_sorties_aircraft_id_aircraft')),
    sa.ForeignKeyConstraint(['engine_start_event_id'], ['tracking_events.id'], name=op.f('fk_sorties_engine_start_event_id_tracking_events')),
    sa.ForeignKeyConstraint(['engine_stop_event_id'], ['tracking_events.id'], name=op.f('fk_sorties_engine_stop_event_id_tracking_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sorties'))
    )
    op.create_index(op.f('ix_sorties_aircraft_id'), 'sorties', ['aircraft_id'], unique=False)
    op.create_table('sortie_waypoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sortie_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('location_method', sa.Enum('latlon', 'mgrs', 'named_point', name='waypointlocationmethod'), nullable=False),
    sa.Column('raw_input', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Float(), nullable=True),
    sa.Column('fuel_remaining_hours', sa.Integer(), nullable=True),
    sa.Column('fuel_remaining_minutes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['tracking_events.id'], name=op.f('fk_sortie_waypoints_event_id_tracking_events')),
    sa.ForeignKeyConstraint(['sortie_id'], ['sorties.id'], name=op.f('fk_sortie_waypoints_sortie_id_sorties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sortie_waypoints'))
    )
    op.create_index(op.f('ix_sortie_waypoints_sortie_id'), 'sortie_waypoints', ['sortie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Not implemented -- same reason as b286fc804e53/8db027860662: this migration
    # also adds eventtype enum values, which Postgres cannot drop without rebuilding
    # the type. Not worth a partial downgrade (tables only, enum values left behind).
    raise NotImplementedError("Cannot drop an enum value in Postgres without rebuilding the type")
