"""add aircraft_callsigns table for PARD/multi-callsign support

Revision ID: 52d975c226ce
Revises: 6d4e2b605bfb
Create Date: 2026-09-12 11:19:49.979531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d975c226ce'
down_revision: Union[str, Sequence[str], None] = '6d4e2b605bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_callsigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('fk_aircraft_callsigns_aircraft_id_aircraft')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aircraft_callsigns'))
    )
    op.create_index(op.f('ix_aircraft_callsigns_aircraft_id'), 'aircraft_callsigns', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_aircraft_callsigns_callsign'), 'aircraft_callsigns', ['callsign'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircraft_callsigns_callsign'), table_name='aircraft_callsigns')
    op.drop_index(op.f('ix_aircraft_callsigns_aircraft_id'), table_name='aircraft_callsigns')
    op.drop_table('aircraft_callsigns')
    # ### end Alembic commands ###
