"""baseline: existing schema

Revision ID: 6d4e2b605bfb
Revises: 
Create Date: 2026-09-12 08:14:38.728850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4e2b605bfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_tracking_events_airfield_id_airfields'), 'tracking_events', 'airfields', ['airfield_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tracking_events_airfield_id_airfields'), 'tracking_events', type_='foreignkey')
    # ### end Alembic commands ###
