"""add default_pic_name to aircraft

Revision ID: 96100adb63e5
Revises: 11620fb9de27
Create Date: 2026-09-13 07:06:03.138935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96100adb63e5'
down_revision: Union[str, Sequence[str], None] = '11620fb9de27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('default_pic_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'default_pic_name')
    # ### end Alembic commands ###
