"""add discovered_callsigns table

Revision ID: 9865f48d7275
Revises: a5dea6a1fd30
Create Date: 2026-09-15 13:23:32.838391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9865f48d7275'
down_revision: Union[str, Sequence[str], None] = 'a5dea6a1fd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_callsigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tail_number', sa.String(length=10), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_callsigns')),
    sa.UniqueConstraint('tail_number', 'callsign', name='uq_discovered_tail_callsign')
    )
    op.create_index(op.f('ix_discovered_callsigns_tail_number'), 'discovered_callsigns', ['tail_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_callsigns_tail_number'), table_name='discovered_callsigns')
    op.drop_table('discovered_callsigns')
    # ### end Alembic commands ###
