"""link tracking events and takeoff/landing to sortie

Revision ID: b3ec32e22ace
Revises: 96100adb63e5
Create Date: 2026-09-14 13:45:39.122297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ec32e22ace'
down_revision: Union[str, Sequence[str], None] = '96100adb63e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorties', sa.Column('takeoff_event_id', sa.UUID(), nullable=True))
    op.add_column('sorties', sa.Column('landing_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_sorties_takeoff_event_id_tracking_events'), 'sorties', 'tracking_events', ['takeoff_event_id'], ['id'])
    op.create_foreign_key(op.f('fk_sorties_landing_event_id_tracking_events'), 'sorties', 'tracking_events', ['landing_event_id'], ['id'])
    op.add_column('tracking_events', sa.Column('sortie_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tracking_events_sortie_id'), 'tracking_events', ['sortie_id'], unique=False)
    op.create_foreign_key(op.f('fk_tracking_events_sortie_id_sorties'), 'tracking_events', 'sorties', ['sortie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tracking_events_sortie_id_sorties'), 'tracking_events', type_='foreignkey')
    op.drop_index(op.f('ix_tracking_events_sortie_id'), table_name='tracking_events')
    op.drop_column('tracking_events', 'sortie_id')
    op.drop_constraint(op.f('fk_sorties_landing_event_id_tracking_events'), 'sorties', type_='foreignkey')
    op.drop_constraint(op.f('fk_sorties_takeoff_event_id_tracking_events'), 'sorties', type_='foreignkey')
    op.drop_column('sorties', 'landing_event_id')
    op.drop_column('sorties', 'takeoff_event_id')
    # ### end Alembic commands ###
