"""add faa hub type classification to airfields

Revision ID: a5dea6a1fd30
Revises: b3ec32e22ace
Create Date: 2026-09-14 19:01:00.088292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dea6a1fd30'
down_revision: Union[str, Sequence[str], None] = 'b3ec32e22ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airfields', sa.Column('hub_type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airfields', 'hub_type')
    # ### end Alembic commands ###
