"""add special use airspace and gis layer tables

Revision ID: 9d49af6c2734
Revises: b286fc804e53
Create Date: 2026-09-12 16:02:46.673087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '9d49af6c2734'
down_revision: Union[str, Sequence[str], None] = 'b286fc804e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('special_use_airspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('lower_altitude', sa.String(length=20), nullable=True),
    sa.Column('upper_altitude', sa.String(length=20), nullable=True),
    sa.Column('times_of_use', sa.String(length=200), nullable=True),
    sa.Column('geometry', Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_special_use_airspace'))
    )
    op.create_geospatial_index('idx_special_use_airspace_geometry', 'special_use_airspace', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_special_use_airspace_source_id'), 'special_use_airspace', ['source_id'], unique=True)
    op.create_index(op.f('ix_special_use_airspace_state'), 'special_use_airspace', ['state'], unique=False)
    op.create_index(op.f('ix_special_use_airspace_type_code'), 'special_use_airspace', ['type_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_use_airspace_type_code'), table_name='special_use_airspace')
    op.drop_index(op.f('ix_special_use_airspace_state'), table_name='special_use_airspace')
    op.drop_index(op.f('ix_special_use_airspace_source_id'), table_name='special_use_airspace')
    op.drop_geospatial_index('idx_special_use_airspace_geometry', table_name='special_use_airspace', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('special_use_airspace')
    # ### end Alembic commands ###
